const tableData = [
  {
    DOMAIN: 'Expected Output',

    'TEST DATA 1': 'QUERY',
    'TEST DATA 2': 'NO Query',
    'TEST DATA 3': 'Query',
    'TEST DATA 4': 'Query',
    'TEST DATA 5': 'NO Query',
    'TEST DATA 6': 'Query',
    'TEST DATA 7': 'Query',
    'TEST DATA 8': 'Query',
    'TEST DATA 9': 'Query',
    'TEST DATA 10': 'No Query',
  },
  {
    DOMAIN: 'Actual Output',
    'TEST DATA 1': '',
    'TEST DATA 2': '',
    'TEST DATA 3': '',
    'TEST DATA 4': '',
    'TEST DATA 5': '',
    'TEST DATA 6': '',
    'TEST DATA 7': '',
    'TEST DATA 8': '',
    'TEST DATA 9': '',
    'TEST DATA 10': '',
  },
  {
    DOMAIN: 'Result',

    'TEST DATA 1': '',
    'TEST DATA 2': '',
    'TEST DATA 3': '',
    'TEST DATA 4': '',
    'TEST DATA 5': '',
    'TEST DATA 6': '',
    'TEST DATA 7': '',
    'TEST DATA 8': '',
    'TEST DATA 9': '',
    'TEST DATA 10': '',
  },
  {
    DOMAIN: 'AE',
    DATASET: 'AESTDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
  {
    DOMAIN: ' ',
    DATASET: 'AEENDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
  {
    DOMAIN: 'CM',
    DATASET: 'CMSTDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
  {
    DOMAIN: ' ',
    DATASET: 'CMENDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
  {
    DOMAIN: 'DM',
    DATASET: 'DMSTDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
  {
    DOMAIN: ' ',
    DATASET: 'DMENDT',
    'TEST DATA 1': 'value',
    'TEST DATA 2': 'value',
    'TEST DATA 3': 'value',
    'TEST DATA 4': 'value',
    'TEST DATA 5': 'value',
    'TEST DATA 6': 'value',
    'TEST DATA 7': 'value',
    'TEST DATA 8': 'value',
    'TEST DATA 9': 'value',
    'TEST DATA 10': 'value',
  },
]

const pinnedBottomRowData = []
export { tableData, pinnedBottomRowData }
